version: "3"
services:
    web:
        image: craigderington/pyshorty:latest
        ports:
            - "5580:5580"
    redis:
        image: redis:latest
        ports:
            - "6379:6379"  